apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift
  namespace: vanilla-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
        sidecar.istio.io/inject: 'false'
      annotations:
        #status.sidecar.istio.io/port: "0"
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-openshift
  namespace: vanilla-playground
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  selector:
    app: hello-openshift